feat: Support customization of doubleTap delay
leancodepl/patrol pull request #2165
Opened 2024-03-27 16:53 UTC by Akshatji800

## Resolves: #2164 

## Issue:
Wanted to have a test where my use-case was replication of user behaviour who quickly click on back button twice. Thought of using doubleTap() but it doesn't serve the purpose due to the 300 ms delay given by default according to the below code snippet.

## Changes Made:
Implemented a way that the delay between the doubleTap can be customized by the user itself. Also used a different logic for doubleTap instead of directly using `uiObject.click()` twice as it was having a bit of delay in functioning by default.

2024-04-25 07:13 UTC, piotruela requested changes
Files like `Contracts.kt`, `contracts.dart` and `contracts.g.dart` shouldn't be modified by hand. Look for 
```dart
///
//  Generated code. Do not modify.
//  source: schema.dart
//
``` 
header in those files. 
Instead, add define a field that you want to add to the method inside `schema.dart` and run `gen_from_schema` script to regenerate the contracts

2024-04-25 11:25 UTC, Akshatji800 commented
> Files like `Contracts.kt`, `contracts.dart` and `contracts.g.dart` shouldn't be modified by hand. Look for
> 
> ```dart
> ///
> //  Generated code. Do not modify.
> //  source: schema.dart
> //
> ```
> 
> header in those files. Instead, define a field that you want to add to the method inside `schema.dart` and run `gen_from_schema` script to regenerate the contracts

Hey @piotruela I have made the changes requested. Can you please review again and let me know if anything else is needed to be done from my side.

2024-04-26 05:25 UTC, piotruela reviewed
One more thing. Let's update the documentation of `doubleTap` method in `native_automator.dart` and `native_automator2.dart` so that it will be clear for the user that `delayBetweenTaps` is for now only respected for Android.

2024-04-29 07:23 UTC, Akshatji800 commented
> One more thing. Let's update the documentation of `doubleTap` method in `native_automator.dart` and `native_automator2.dart` so that it will be clear for the user that `delayBetweenTaps` is for now only respected for Android.

Hey @piotruela, I have made the suggested changes. Can you please look at it again and let me know if anything else is needed from my side.

2024-04-29 07:46 UTC, piotruela approved these changes
lgtm 👍

2024-04-29 07:46 UTC, merged