Implement native scrollTo for iOS
leancodepl/patrol pull request #2343
Opened 2024-09-20 14:38 UTC by piotruela

2024-10-01 12:29 UTC, mateuszwojtczak requested changes

2024-10-01 15:12 UTC, piotruela commented on packages/patrol/CHANGELOG.md
> +
`minSdkVersion` is bumped in `e2e_app` and `example` to fix dexing errors when building Android app with Flutter `3.24.3`.

2024-10-01 15:14 UTC, piotruela commented on packages/patrol/darwin/Classes/AutomatorServer/Automator/IOSAutomator.swift
> +        let startCoordinate = app.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.9))
We are performing custom gesture here, to scroll down while searching for element.
`CGVector(dx: 0.5, dy: 0.9)` - (close to) bottom of the screen,
`CGVector(dx: 0.5, dy: 0.1)` - (close to) top of the screen,

2025-07-25 07:14 UTC, Kendru98 commented
Can be used in enableDarkmode method, because now we just swipe down once to scroll for Developer settings

2026-07-31 22:54 UTC, closed without merging