fix: Modify test names inside PatrolJUnitRunner to remove spaces
leancodepl/patrol pull request #2361
Opened 2024-10-08 12:05 UTC by piotruela

Replaces spaces in the name returned by `listDartTest` with a version that does not contain spaces.
The change is also visible in the report, as it reflects the names of the tests (functions) that are executed as tests.

2024-10-08 12:27 UTC, pdenert reviewed
Looks good, but you have to add changelog, bump package version and update compatibility table

2024-10-08 12:33 UTC, mateuszwojtczak requested changes

2024-10-08 13:26 UTC, pdenert approved these changes
lgtm

2024-10-08 13:32 UTC, mateuszwojtczak approved these changes

2024-10-08 13:33 UTC, merged

2024-10-10 09:44 UTC, Wreos commented
Should I update "androidx.test:orchestrator version as well? Currently I have 1.4.2 (as in documentation)

Because after updating to Patrol 3.11.1 I have another problem when run tests in firebase
`java.lang.RuntimeException: Could not open stream for output
     FATAL EXCEPTION: AndroidTestOrchestrator
Process: androidx.test.orchestrator, PID: 8626
java.lang.RuntimeException: Could not open stream for output
	at androidx.test.orchestrator.AndroidTestOrchestrator.getOutputStream(AndroidTestOrchestrator.java:5)
	at androidx.test.orchestrator.AndroidTestOrchestrator.executeNextTest(AndroidTestOrchestrator.java:11)
	at androidx.test.orchestrator.AndroidTestOrchestrator.runFinished(AndroidTestOrchestrator.java:10)
	at androidx.test.orchestrator.TestRunnable.run(TestRunnable.java:11)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)`

2024-10-11 06:44 UTC, piotruela commented
Hi @Wreos. I suspect you've encountered [this issue](https://github.com/leancodepl/patrol/issues/1725). Patrol `3.11.1` modifies the test name to comply with the requirements of the new orchestrator version which is used on Firebase Test Lab. Probably after the modification, your test name is not a bit too long. Yes, you can try bumping `androidx.test:orchestrator` version to 1.5.0 in your project. Alternatively you can try modifying test names to be shorter. 
Let me know it helps.

2024-12-09 04:10 UTC, tddang-linagora commented
Hi @Wreos 

The `androidx.test:orchestrator` dependency only matters in your own local test environment. Firebase Test Lab ignores that and always runs with the latest version. 

>Because after updating to Patrol 3.11.1 I have another problem when run tests in firebase

If your project is able to run on Flutter 3.24.x, you can upgrade Patrol and its CLI to the latest version to resolve your issue. Our team's project is stuck with 3.22.x, so we reverted our Patrol dependency version to 3.11.0 and that fixed our Firebase test crash too.

Hope this helps you.

2024-12-09 10:35 UTC, Wreos commented
> Hi @Wreos
> 
> The `androidx.test:orchestrator` dependency only matters in your own local test environment. Firebase Test Lab ignores that and always runs with the latest version.
> 
> > Because after updating to Patrol 3.11.1 I have another problem when run tests in firebase
> 
> If your project is able to run on Flutter 3.24.x, you can upgrade Patrol and its CLI to the latest version to resolve your issue. Our team's project is stuck with 3.22.x, so we reverted our Patrol dependency version to 3.11.0 and that fixed our Firebase test crash too.
> 
> Hope this helps you.

Big thanks for your feedback, for now everything works fine for me with latest version Patrol and Flutter 😄 
But in the past, to make everything work after this [change](https://github.com/leancodepl/patrol/pull/2361)  I had to shorten the test names and change the spaces to _