Added a Lambdatest runner to execute the patrol test.
leancodepl/patrol pull request #2424
Opened 2024-11-21 20:14 UTC by Gauravpandeyr

2024-11-27 10:35 UTC, mateuszwojtczak requested changes
Also, let's add some page to the docs in the "Integrations" section

2024-11-27 10:35 UTC, mateuszwojtczak commented on packages/patrol/example/android/app/build.gradle
let's remove this change

2024-11-27 10:35 UTC, mateuszwojtczak commented on packages/patrol/example/android/app/src/androidTest/java/pl/leancode/patrol/example/MainActivityTest.java
let's remove this change

2024-11-27 10:35 UTC, mateuszwojtczak commented on packages/patrol/example/android/gradle.properties
let's remove this change

2024-11-27 10:35 UTC, mateuszwojtczak commented on packages/patrol/example/android/settings.gradle
let's remove this change

2024-11-27 10:35 UTC, mateuszwojtczak commented on packages/patrol/android/src/main/kotlin/pl/leancode/patrol/LambdaTestPatrolJUnitRunner.java
> +public class LambdatestPatrolJUnitRunner extends PatrolJUnitRunner {
```suggestion
public class LambdaTestPatrolJUnitRunner extends PatrolJUnitRunner {
```

2024-11-27 10:35 UTC, mateuszwojtczak commented on packages/patrol/android/src/main/kotlin/pl/leancode/patrol/LambdaTestPatrolJUnitRunner.java
> +            //TODO verify in a project where we use LambdaTest
remove this TODO

2024-11-27 18:13 UTC, Gauravpandeyr reviewed
These were originally present in the repository, I have added them back. The only change is in the LambdaTestPatrolJUnitRunner.java file only. Everything else is exactly the same.

2024-11-27 18:13 UTC, Gauravpandeyr commented on packages/patrol/android/src/main/kotlin/pl/leancode/patrol/LambdaTestPatrolJUnitRunner.java
> +            //TODO verify in a project where we use LambdaTest
Removed

2024-11-27 18:13 UTC, Gauravpandeyr commented on packages/patrol/example/android/app/build.gradle
Not a change.

2024-11-27 18:13 UTC, Gauravpandeyr commented on packages/patrol/example/android/app/src/androidTest/java/pl/leancode/patrol/example/MainActivityTest.java
Not a change

2024-11-27 18:13 UTC, Gauravpandeyr commented on packages/patrol/example/android/gradle.properties
Not a change

2024-11-27 18:13 UTC, Gauravpandeyr commented on packages/patrol/example/android/settings.gradle
Not a change

2024-12-04 14:37 UTC, Gauravpandeyr commented
> Also, let's add some page to the docs in the "Integrations" section

Added the doc:
https://github.com/leancodepl/patrol/pull/2424/files#diff-79e29b3af6a95e45d7a1250a3b5e23db3513950c6fed17874cef02a5dc15ba2

2024-12-09 15:21 UTC, closed without merging