Add android flavor to dartDefines.
leancodepl/patrol pull request #2425
Opened 2024-11-22 11:34 UTC by GChanathip

this PR fix issue https://github.com/leancodepl/patrol/issues/2256

2024-11-25 15:46 UTC, piotruela requested changes
Thanks for the contribution!
Overall lgtm, just a small nitpick.
Please also add an entry to changelog.

2024-11-25 15:46 UTC, piotruela commented on packages/patrol_cli/lib/src/crossplatform/app_options.dart
> +    }
Nit:
```suggestion
    if (flutter.flavor case final flavor?) {
      effectiveDartDefines['FLUTTER_APP_FLAVOR'] = flavor;
    }
```
To get rid of bang operator

2024-11-26 05:20 UTC, GChanathip commented on packages/patrol_cli/lib/src/crossplatform/app_options.dart
> +    }
Thanks for your suggestion.

2024-11-26 07:43 UTC, piotruela commented on packages/patrol_cli/CHANGELOG.md
> +## 3.5.0
No need to specify the version just yet. Use `## Unreleased` instead

2024-11-26 08:33 UTC, piotruela approved these changes
All good! 🙌

2024-11-26 08:34 UTC, merged