Use protobuf
leancodepl/patrol pull request #338
Opened 2022-09-22 07:51 UTC by bartekpacia

2022-09-22 15:05 UTC, bartekpacia commented on AutomatorServer/android/app/src/androidTest/java/pl/leancode/automatorserver/PatrolAutomator.kt
> +    fun swipe(swipe: Contracts.SwipeCommand) {
I hate this prefix but haven't found a way to get rid of this. Same on Swift side.

2022-09-22 15:05 UTC, bartekpacia commented on contracts.proto
> +}
all the "commands" and "queries" are gonna get GRPC-ed in the next PR (or maybe this one? idk).

2022-09-26 14:22 UTC, Xezolpl requested changes

2022-09-26 14:29 UTC, Xezolpl requested changes

2022-09-26 14:29 UTC, Xezolpl commented on AutomatorServer/ios/AutomatorServerUITests/PatrolAutomation.swift
> +    runAction("enabling wifi") {
```suggestion
    runAction("disabling wifi") {
```

2022-09-26 15:09 UTC, jakubfijalkowski commented on gen_protobufs
> +    --grpckt_out="$kotlin_out" \
Indent

2022-09-26 17:58 UTC, bartekpacia commented on AutomatorServer/ios/AutomatorServerUITests/PatrolAutomation.swift
> +
yeah, Xcode moment.

I used to treat everything with `swift-format` but after upgrading to Xcode 14, `swift-format` kind of died and refuses to work.

2022-09-26 17:59 UTC, bartekpacia commented on AutomatorServer/ios/AutomatorServerUITests/PatrolAutomation.swift
> +    runAction("enabling wifi") {
Haha, thanks!

2022-09-26 18:07 UTC, bartekpacia commented on gen_protobufs
> +    --grpckt_out="$kotlin_out" \
fix'd

2022-09-26 18:09 UTC, bartekpacia commented on packages/patrol/example/integration_test/ios/devel_test.dart
> +      $.log('test end');
nowhere:P

this file was a copy-pasted debugging aid. I removed it now. Thanks.

2022-09-26 18:51 UTC, merged