Make `--target` flag accept directories
leancodepl/patrol pull request #473
Opened 2022-10-18 20:09 UTC by bartekpacia

This PR:
- fixes #472

2022-10-18 20:39 UTC, PiotrRogulski requested changes

2022-10-18 21:16 UTC, bartekpacia commented on packages/patrol_cli/lib/src/features/drive/test_finder.dart
> +    directory ??= _integrationTestDirectory;
This is a recommended and preferred workaround around this – [learn more here](https://dart-lang.github.io/linter/lints/parameter_assignments.html). Linter is perfectly happy with this.

2022-10-18 21:17 UTC, bartekpacia commented on packages/patrol_cli/test/features/drive/test_finder_test.dart
> +            .directory('integration_test/features/login')
yeah it is, but it's also what `dart format` outputs... will try to improve things but doubt I'll succeed 😅

2022-10-18 21:26 UTC, bartekpacia commented on packages/patrol_cli/lib/src/features/drive/test_finder.dart
> +          ..removeAt(i);
Nice idea, `n` will be always small so the performance hit is negligible. Thanks!

2022-10-18 21:30 UTC, bartekpacia commented on packages/patrol_cli/test/features/drive/test_finder_test.dart
> +            .directory('integration_test/features/login')
OK, I managed to fit this into a single line.

2022-10-18 21:37 UTC, PiotrRogulski commented on packages/patrol_cli/lib/src/features/drive/test_finder.dart
> +    directory ??= _integrationTestDirectory;
Ok, I was using a different operator :+1:

2022-10-19 06:48 UTC, merged

2022-10-19 06:48 UTC, shilangyu approved these changes